### ISSUE TITLE
Add "hello world" landing page

### ISSUE THREAD

**Issue by tomkersten** [DanTheMan0000/koa-hello-world#1]
By cloning this repository and running the following commands:

```
$ npm install
$ npm start
```

We want to be able to go to:

http://127.0.0.1:8000/

And see a  message of "Hello World" in a web browser, rendered with a "Content-Type" header of `text/html`.

Ping me in the Slack when you run into issues and drop a message in here when you "think" you're done. ;)

**Comment by DanTheMan0000** [comment]
I have completed creating a "hello world" landing page.

**Comment by tomkersten** [comment]
Your "Content-Type" response headers are not correct. :wink: Needs to be "text/html", right now, it "application/json".

You can check this by running `curl -v http://127.0.0.1:8000` in your terminal, or by looking in the "Network" tab of Chrome's developer console.

Take a screenshot of both of those things and put in here so I know you have found both methods. ;-)

**Comment by DanTheMan0000** [comment]
<img width="342" alt="screen shot 2016-08-25 at 3 28 31 pm" src="https://cloud.githubusercontent.com/assets/19934523/17984879/dd57e2da-6ad8-11e6-961c-abf17db62ae8.png">
<img width="383" alt="screen shot 2016-08-25 at 3 28 44 pm" src="https://cloud.githubusercontent.com/assets/19934523/17984884/e63aa388-6ad8-11e6-8242-8d29fef331c5.png">
here they are

**Comment by tomkersten** [comment]
Cool. Now make it return `text/html` there instead. ;-)

Hint: 

``` javascript
ctx.type = 'html';
```

...should do it. ;-)

**Comment by tomkersten** [comment]
Why was this closed? It looks like it is still rendering the incorrect header value. :wink:

**Comment by DanTheMan0000** [comment]
Isn't this the right header:
![image](https://cloud.githubusercontent.com/assets/19934523/18333278/32813a36-7533-11e6-86fb-107904b1f5bf.png)

**Comment by DanTheMan0000** [comment]
forgot to "push it" that was probably the problem
