### ISSUE TITLE
Not getting the server to say "Hello World"

### ISSUE THREAD

**Issue by DanTheMan0000** [DanTheMan0000/koa-hello-world#5]
I can get to the server but it keeps printing out "not found", i've been trying a couple things but they have not been working. I assume the problem is in this part of the code:
router.get('/:8000', (ctx , next) => {
  ctx.body = ("Hello World");
  ctx.type = 'json';
});
but I am not completely sure.

**Comment by tomkersten** [comment]
Remove the `:8000` from your route definition. That's only necessary when you use the browser to retrieve a page (ie: http://127.0.0.1:8000/). 

In this context, your route _could_ be something like:

``` javascript
router.get('/:name', (ctx, next) => {
///code here
});
```

..and then you could hit http://127.0.0.1:8000/dan and retrieve the value 'dan' inside that `///code here` section of code.

Make sense?

**Comment by DanTheMan0000** [comment]
so all i have to do is remove :8000,because that is used for when i am searching for it on a browser, and i can just use a link like [http://127.0.0.1:8000/dan](url) to get to it.

**Comment by tomkersten** [comment]
you will have to remove `/dan` from the URL you visit in the browser...but the rest is correct. ;)

**Comment by DanTheMan0000** [comment]
ya my bad forgot to do that.
