### ISSUE TITLE
Render HTML page

### ISSUE THREAD

**Issue by tomkersten** [DanTheMan0000/koa-hello-world#7]
Figure out how to "serve" a static HTML file + assets (images, CSS files, etc).

Start by downloading the HTML5 boilerplate site [here](https://html5boilerplate.com/).

You should probably use another `koa` middleware named `koa-static` (available [here](https://github.com/koajs/static)).

This task will be complete when I can visit http://127.0.0.1:8000 in a browser and see the HTML5 boilerplate page.

May the odds be ever in your favor... :wink:

**Comment by DanTheMan0000** [comment]
Hey, I have put the html5 boilerplate into the public folder and all of that stuff, but I can not get it to display the boilerplate backround.

**Comment by tomkersten** [comment]
sorry about this...i responded to the notification, assuming it would post here. I was wrong and it got lost.

From my email:

> Push your current state to Github. Also, check the dev console for errors and 404's (console tab and network tab)

**Comment by tomkersten** [comment]
Take a peek now, @DanTheMan0000. Also note the comments on the diff in 4e1a91b3047ec76a358c012b96aa42a24c495c95.

**Comment by tomkersten** [comment]
This is done as of 4e1a91b.
